# Generated by Django 5.0 on 2024-03-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tourcode', models.CharField(max_length=10, unique=True)),
                ('tourname', models.CharField(max_length=30)),
                ('tourpackage', models.CharField(max_length=35)),
                ('desc', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'package_table1',
            },
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
