# Generated by Django 5.0 on 2024-03-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_packages1_delete_packages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packages1',
            table='package_table',
        ),
    ]
