# Generated by Django 5.0 on 2024-03-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_packages1_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages1',
            new_name='Packages',
        ),
    ]
