# Generated by Django 5.0 on 2024-03-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_packages_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tourrcode', models.CharField(max_length=10, unique=True)),
                ('tourrname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'packages_table',
            },
        ),
    ]
